/** Shared inline styles — dark, compact, matching the S&S panel aesthetic. */

import type { CSSProperties } from 'react';

export const palette = {
  text: 'rgba(235, 235, 245, 0.92)',
  textDim: 'rgba(235, 235, 245, 0.55)',
  textFaint: 'rgba(235, 235, 245, 0.35)',
  cardBg: 'rgba(255, 255, 255, 0.04)',
  cardBorder: 'rgba(255, 255, 255, 0.08)',
  accent: '#8b7cf6',
  accentSoft: 'rgba(139, 124, 246, 0.18)',
  danger: '#e06c75',
  chipBg: 'rgba(255, 255, 255, 0.07)',
  chipActiveBg: 'rgba(139, 124, 246, 0.28)',
};

export const styles: Record<string, CSSProperties> = {
  panel: { padding: '10px 12px 14px', color: palette.text, fontSize: 12 },
  emptyState: { padding: '18px 6px', color: palette.textDim, textAlign: 'center' },
  errorBar: {
    margin: '6px 0',
    padding: '6px 8px',
    borderRadius: 6,
    background: 'rgba(224, 108, 117, 0.12)',
    border: `1px solid rgba(224, 108, 117, 0.35)`,
    color: palette.danger,
    whiteSpace: 'pre-wrap',
  },
  card: {
    margin: '8px 0',
    padding: '8px 10px',
    borderRadius: 8,
    background: palette.cardBg,
    border: `1px solid ${palette.cardBorder}`,
  },
  cardHeader: { display: 'flex', alignItems: 'center', gap: 8 },
  cardTitle: { fontWeight: 600, fontSize: 12.5 },
  cardBlurb: { color: palette.textFaint, fontSize: 10.5, margin: '2px 0 6px' },
  row: { display: 'flex', alignItems: 'center', gap: 8, margin: '5px 0', flexWrap: 'wrap' },
  label: { color: palette.textDim, fontSize: 10.5, minWidth: 52 },
  chip: {
    padding: '2px 8px',
    borderRadius: 10,
    background: palette.chipBg,
    border: '1px solid transparent',
    color: palette.textDim,
    cursor: 'pointer',
    fontSize: 10.5,
    userSelect: 'none',
  },
  chipActive: {
    background: palette.chipActiveBg,
    border: `1px solid ${palette.accent}`,
    color: palette.text,
  },
  select: {
    background: 'rgba(0,0,0,0.25)',
    color: palette.text,
    border: `1px solid ${palette.cardBorder}`,
    borderRadius: 4,
    fontSize: 11,
    padding: '2px 4px',
  },
  slider: { flex: 1, minWidth: 90, accentColor: palette.accent },
  iconButton: {
    background: 'transparent',
    border: 'none',
    color: palette.textDim,
    cursor: 'pointer',
    fontSize: 13,
    padding: '0 4px',
  },
  addButton: {
    background: palette.accentSoft,
    color: palette.text,
    border: `1px solid ${palette.accent}`,
    borderRadius: 6,
    padding: '4px 12px',
    cursor: 'pointer',
    fontSize: 12,
  },
  menu: {
    margin: '8px 0',
    padding: 8,
    borderRadius: 8,
    background: 'rgba(20, 20, 28, 0.97)',
    border: `1px solid ${palette.cardBorder}`,
  },
  menuFamily: { color: palette.textFaint, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1, margin: '6px 0 3px' },
  menuItem: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    background: 'transparent',
    border: 'none',
    color: palette.text,
    padding: '4px 6px',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 11.5,
  },
};
